### ISSUE TITLE
about offline RL

### ISSUE THREAD

**Issue by guchi-ac** [vita-epfl/social-nce#12]
I have read your article（Social-NCE） carefully and am very interested in the part about offline reinforcement learning, but I don't seem to find the corresponding part in this code. Can you tell me how to get it? or can you give me some recommended codes?

**Comment by qiyan98** [comment]
Hi there,

We use the [CrowdNav](https://github.com/vita-epfl/CrowdNav) benchmark to set up the RL task. We collected the data for offline RL when training our rainbow DQN.

The key steps to collect data are:
```(i) 10k episodes are collected during online RL training from scratch, (ii) multiple free explorations are carried out using online RL checkpoint models trained after K episodes, where K ∈ {500, 1000, 3000, 5000}```.
The offline RL data was collected from the training or simulations in CrowdNav environment. We believe this example showcases the general applicability of our proposed constrastive representation learning technique.
