### ISSUE TITLE
I cannot find "Imitator" in crowd_nav.utils.trainer

### ISSUE THREAD

**Issue by yyf17** [vita-epfl/social-nce#4]
Thank you for your hard work.
in the file "crowd_nav/utils/demonstrate.py"
```
   from crowd_nav.utils.frames import FrameStack
  from crowd_nav.utils.trainer import Imitator
  from crowd_nav.utils.memory import ReplayMemory

```

I cannot find "Imitator" in crowd_nav.utils.trainer.
will you help me ?

**Comment by YuejiangLIU** [comment]
Sorry for answering late. The line involving `Imitator` is obsolete and can be removed. Please check out the latest commit, which should have resolved this issue.
