### ISSUE TITLE
What does SAIL refer to?

### ISSUE THREAD

**Issue by chenzhutian** [vita-epfl/social-nce#7]
Thanks for your wonderful repo!
May I ask what does SAIL policy refer to?
Based on the paper I only find SARL but not SAIL. Is SAIL an upgrade version of SARL?
Thanks!

**Comment by YuejiangLIU** [comment]
Thanks for your interest in our work.

The SAIL refers to socially attentive imitation learning, a model used in our [Social-NCE](https://openaccess.thecvf.com/content/ICCV2021/papers/Liu_Social_NCE_Contrastive_Learning_of_Socially-Aware_Motion_Representations_ICCV_2021_paper.pdf) paper.

The key differences between SAIL and SARL proposed in our CrowdNav paper are the following, 
- SAIL is a policy net that directly outputs an action, whereas SARL is a value net with a discrete action space.
- In addition to the action, SAIL also outputs the encoded feature vector, which is robustified by our proposed social contrastive loss during training.
- SAIL contains fewer parameters than the SARL. We empirically find that removing some dense MLPs makes the SAIL easier and faster to train, without degrading the performance.

**Comment by chenzhutian** [comment]
Awesome! Thanks for your explanation and will look into the details.
I am currently working on a project based on your works. It is not for robots but for user interfaces, though.
I am also wondering have you tried the GA3C method mentioned in [1]?

Thanks!

[1] Michael Everett‡ , Yu Fan Chen† , and Jonathan P. How‡. Motion Planning Among Dynamic, Decision-Making Agents with Deep Reinforcement Learning.

**Comment by chenzhutian** [comment]
Another thing is that I would like to remove the imitation in SAIL and only use it to control an agent (eg, following a target while avoiding collision), is this possible?

Thanks again~

**Comment by chenzhutian** [comment]
One more question about SAIL 😃  -
it seems the state is also different from SARL? The robot state is (px, py, vx, vy, gx, gy) and the human state is (px, py, vx, vy). Are these in the robot center coordination? I can find the code (eg, the `rotate` function used in SARL) to transfer the coordination.

Best

**Comment by YuejiangLIU** [comment]
> Awesome! Thanks for your explanation and will look into the details. I am currently working on a project based on your works. It is not for robots but for user interfaces, though. I am also wondering have you tried the GA3C method mentioned in [1]?
> 
> Thanks!
> 
> [1] Michael Everett‡ , Yu Fan Chen† , and Jonathan P. How‡. Motion Planning Among Dynamic, Decision-Making Agents with Deep Reinforcement Learning.

As far as I remember, the GA3C was actually one of the baselines in our CrowdNav paper, where we named it as LSTM-RL in order to distinguish its core LSTM module from the attention mechanism used in ours

**Comment by YuejiangLIU** [comment]
> Another thing is that I would like to remove the imitation in SAIL and only use it to control an agent (eg, following a target while avoiding collision), is this possible?
> 
> Thanks again~

It depends on your use case (e.g., environment). 

If your environment is very similar to ours, I believe, you can try and use an already trained SAIL. Else if there is a clear domain shift, I'm afraid the model has to be adapted accordingly.

**Comment by YuejiangLIU** [comment]
> One more question about SAIL 😃 - it seems the state is also different from SARL? The robot state is (px, py, vx, vy, gx, gy) and the human state is (px, py, vx, vy). Are these in the robot center coordination? I can find the code (eg, the `rotate` function used in SARL) to transfer the coordination.
> 
> Best

If I remember correctly, they are global coordinates, but I'm not 100% sure. I cannot recall some details, unfortunately. Maybe it's better to verify that by running the code till that line.

**Comment by chenzhutian** [comment]
Great, I will run the code and prob into the details. Thanks!

**Comment by YuejiangLIU** [comment]
I'm closing the issue for now. Please feel free to open a new one, if you encounter any other questions later on.
